inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable

Layout/ParameterAlignment:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/LineLength:
  Max: 130

Style/NumericPredicate:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
    - Rakefile
    - activerecord-postgis-adapter.gemspec
    - gemfiles/*
